debug: ${DEBUG_MODE|false}
formatMessage: "🎂 ДР {fullname} | {soon_time} \n\n📆 {date}"

database:
  enabled: true
  host: ${DB_HOST}
  name: ${DB_NAME}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASS}
  migrations: migrations
  sslmode: disable
  driver: mysql

tgbot:
  token: ${TG_TOKEN}
  notifyChat: ${TG_CHAT_ID}