version: '3.9'

services:
  app:
    build:
      context: .
    working_dir: /application
    environment:
      DEBUG_MODE: true
      HOST: $DB_HOST
      NAME: $DB_NAME
      PORT: $DB_PORT
      USER: $DB_USER
      PASSWORD: $DB_PASSWORD
      BOT_TOKEN: $TG_TOKEN
      BOT_NOTIFYCHAT: $TG_CHAT_ID
      CRON_RULE: "* * * * *"
    volumes:
        - ./app:/application
    command: > 
       /bin/sh -c "go mod download && go run cmd/birth_minder/main.go"