name: Dev

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted
    container: golang:1.13
    steps:
      - name: Build
        run: go build -v ./cmd/birth_minder/main.go
