name: Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOY_PATH: /app/bminder
  BUILD_PATH: bin
  BUILD_APP_NAME: bminder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start build notify
        run: |
          curl https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage -d "text=Начал сборку bminder on prod" -d "chat_id=${{ secrets.CHAT_ID }}"

      - uses: actions/checkout@v7
      - name: tests
        run: ls ~ -la && ls ../ -la

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.26.5
          cache: true

      - name: Build
        run: go mod download && CGO_ENABLED=0 go build -o ./bin/${{ env.BUILD_APP_NAME }} ./cmd/birth_minder/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-files
          path: ${{ env.BUILD_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: start deploy notify
        run: |
          curl https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage -d "text=Начал деплой bminder on prod" -d "chat_id=${{ secrets.CHAT_ID }}"

      - name: Download build files
        uses: actions/download-artifact@v7
        with:
          name: build-files

      - name: test
        run: | 
          echo ${{ secrets.SERVER_IP }} > test.txt
          cat test.txt

      - name: Deploy to prod server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_SECRET_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          debug: true
          envs: TEST=test
          script: |
            cd /app/bminder
            ls -la

      - name: Restart service
        run: sudo systemctl restart ${{ env.BUILD_APP_NAME }}

      - name: success message
        run: |
          curl https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage -d "text=Деплой bminder завершен" -d "chat_id=${{ secrets.CHAT_ID }}"